poll:
  rss_minutes: 10
  watch_seconds: 60
  watch_window_hours: 4

global_webhook_url: "https://discord.com/api/webhooks/1454653384958410907/EfNOPcyGdfU4WzHyE4ElyK1VUcYQ5QcbdH3AXIlZxYyhGvVCpDGfwf-YkAEP-aW79aQa"

committees:
  - name: "Aging"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCIJep6eGHwHaynbF3W-pi4w"
  - name: "Appropriations"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCOfAWcy03u07H8YyZblSbZw"
  - name: "Banking"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHiLcfUQEUhn0SdvHMb77_Q"
  - name: "Children"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCZlIt93Cgqg4ObFitoy6CA"
  - name: "Commerce"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCswa_bKFVx4RLXC2JM_2TxQ"
  - name: "Education"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCraMimcKyMoYpb5ouHG71kw"
  - name: "Energy & Technology"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCwEqhPVSBBZrUUUXB1jJWVg"
  - name: "Environment"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCAnp26iCEXiGvY6rotUkOHg"
  - name: "Executive & Legislative Nominations"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCm6hXVVu0_QYorSbpN5r-sA"
  - name: "Finance, Revenue & Bonding"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_YzYQ37ogO6vBD5izP6xmg"
  - name: "General Law"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCwoAXAEVbgVd8Olzj8L07Og"
  - name: "Government Administration & Elections"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZYYRHzG0LmSkRcG_cCUV5Q"
  - name: "Higher Education & Employment Advancement"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCjlg4Rvko5Yc4_gBmi1VvJg"
  - name: "Human Services"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCRPZ6LdA2yOGUQIRLLqQfEA"
  - name: "Insurance & Real Estate"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWGEqdQAy0I97PqtAgxJCqA"
  - name: "Judiciary"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCaZ1ujQWzOqbtURoR6oTewA"
  - name: "Labor & Public Employees"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUCXzOic28n4vXtOETFVvLA"
  - name: "Planning & Development"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UC3_t7cUwTQZL0jnNY5RDAXg"
  - name: "Public Health"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCe-LxwJs29xhxXSU6xJt_UA"
  - name: "Public Safety & Security"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCwcQuT6Q8-0px-evR5pIumQ"
  - name: "Regulation Review"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMOWtnNOUDJ22IwrRkMc1tQ"
  - name: "Transportation"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsDNKeCbBJrEq2kSCFEncoQ"
  - name: "Veterans' Affairs"
    rss: "https://www.youtube.com/feeds/videos.xml?channel_id=UCirvHxKSiEy8yrE8CwtwoXQ"
